### PR TITLE
Changes to make it compile

### PR DESCRIPTION
**Pull request by sicarul**
Hey Kerry! First of all, amazing work, thanks a lot for open sourcing this! Here is my simple setup working! (no sensors)
image

I came across two issues when trying to install, which didn't show up right away because the build script's `npm run build` doesn't stop on errors, so i followed steps manually until i found the problems:

1) There is a submodule on a private repo, i don't know what it's for, but it seems optional so i removed it.
2) The bluebird promise doesn't work on my raspberry, i say on my raspberry, because curiously this same code compiles on my desktop with Manjaro, i don't know if there's anything special about your setup (I use a Raspberry 4 B with default raspbian) but changing all promises to Bluebird worked for me.

Again, whether you accept these changes or not, i wanted to deeply thank you for this software, i've been looking for something like this for a long time!

### CODE REVIEW

**Comment by kshetline** [comment]
The code you removed is an alternative weather service, proxied from my own web server, which uses my personal subscription to the Weatherbit.io API. Since I wouldn't want that subscription overused, I've put some limits on how many API calls other people can make. It's the details of how that's done which are hidden in the private repo.

But if the code you removed isn't there, then user's don't have a backup weather service when Weather Underground fails.

As for the Bluebird promise thing... that's just weird. I'm using the Raspberry Pi 4 B myself (2 GB version), and haven't had any problems with using promises. Did you have a version of Node.js already installed on your Pi before installing the clock software? Can I see the specific errors you were getting?

**Comment by sicarul** [comment]
Since you require the code:
>   wbProxyForecast = require('./aw-clock-private/weatherbit-proxy').getForecast;
The compilation fails for me at least, how can you require the code if it's hidden? Have you tried running this in a raspberry without ssh access to your github? It doesn't work for me.

I used a fresh install and only installed your software (Which installed node), and i installed nothing else. Maybe it's a versioning thing. I agree it's very weird! Anyway i understand if you don't want to accept these changes, if that's the case at least my fork solves it if someone has the same issues i did. Anyways thanks!!

**Comment by kshetline** [comment]
The `require` is inside a try/catch, so it can fail at runtime if the code isn't available. It should still compile, however. I have and old Raspberry Pi 3 that I've built this code on starting with a completely fresh Raspbian installation, and without entering any of my Github credentials.

I also know other users have built this code successfully, without the build or Promise issues you're having.

I'd love to understand what's not working for you, but for now it's a mystery!

**Comment by sicarul** [comment]
That's very weird indeed, i downloaded a fresh raspbian and only followed the steps. So let's close this and keep this as a hack for any other person that has the same issue. Thanks a lot!

**Comment by kshetline** [comment]
I thought you'd like to know I finally ran into the Bluebird Promise. Even seeing it myself, I don't know quite where it comes from, and why I didn't see the build error until now.

At any rate, it doesn't appear to actually have anything real to do with Bluebird Promises, but rather some TypeScript type definition that must have been updated in an npm library in an incompatible way. I can simply typecast the problem away, and all is good. (Fix it now, understand it later!)

This is the change, at the end of the file tai-utc.ts:

image

You should be all set to use my published updates now, without needing to modify the code yourself to work around this problem.

**Pull request closed without merging**
